#include <stdio.h>
#include <stdlib.h>
#include "funcoes_log.h"

int i = 0, tle = 0, tee = 0;

int main(int argc, char *argv[]) {
ThreadFila *tf = CreateThreadFila();
EntrouNaFila('E',0,tf, &i);
SaiuDaFila('E',0,tf, &i, &tle, &tee);
Executou('E',0,tf, &i, &tle, &tee);
EntrouNaFila('E',0,tf, &i);
SaiuDaFila('E',0,tf, &i, &tle, &tee);
Executou('E',0,tf, &i, &tle, &tee);
EntrouNaFila('E',0,tf, &i);
SaiuDaFila('E',0,tf, &i, &tle, &tee);
EntrouNaFila('E',3,tf, &i);
EntrouNaFila('E',1,tf, &i);
Executou('E',0,tf, &i, &tle, &tee);
EntrouNaFila('E',0,tf, &i);
EntrouNaFila('L',1,tf, &i);
EntrouNaFila('L',0,tf, &i);
SaiuDaFila('E',3,tf, &i, &tle, &tee);
Executou('E',3,tf, &i, &tle, &tee);
EntrouNaFila('E',3,tf, &i);
SaiuDaFila('E',1,tf, &i, &tle, &tee);
Executou('E',1,tf, &i, &tle, &tee);
EntrouNaFila('E',1,tf, &i);
EntrouNaFila('E',2,tf, &i);
SaiuDaFila('E',0,tf, &i, &tle, &tee);
Executou('E',0,tf, &i, &tle, &tee);
EntrouNaFila('E',0,tf, &i);
SaiuDaFila('L',1,tf, &i, &tle, &tee);
Executou('L',1,tf, &i, &tle, &tee);
EntrouNaFila('L',1,tf, &i);
EntrouNaFila('L',3,tf, &i);
SaiuDaFila('L',0,tf, &i, &tle, &tee);
Executou('L',0,tf, &i, &tle, &tee);
EntrouNaFila('L',0,tf, &i);
EntrouNaFila('L',2,tf, &i);
SaiuDaFila('E',3,tf, &i, &tle, &tee);
Executou('E',3,tf, &i, &tle, &tee);
EntrouNaFila('E',3,tf, &i);
SaiuDaFila('E',1,tf, &i, &tle, &tee);
Executou('E',1,tf, &i, &tle, &tee);
EntrouNaFila('E',1,tf, &i);
SaiuDaFila('E',2,tf, &i, &tle, &tee);
Executou('E',2,tf, &i, &tle, &tee);
EntrouNaFila('E',2,tf, &i);
SaiuDaFila('E',0,tf, &i, &tle, &tee);
Executou('E',0,tf, &i, &tle, &tee);
EntrouNaFila('E',0,tf, &i);
SaiuDaFila('L',1,tf, &i, &tle, &tee);
Executou('L',1,tf, &i, &tle, &tee);
EntrouNaFila('L',1,tf, &i);
SaiuDaFila('L',3,tf, &i, &tle, &tee);
Executou('L',3,tf, &i, &tle, &tee);
EntrouNaFila('L',3,tf, &i);
SaiuDaFila('L',0,tf, &i, &tle, &tee);
Executou('L',0,tf, &i, &tle, &tee);
EntrouNaFila('L',0,tf, &i);
SaiuDaFila('L',2,tf, &i, &tle, &tee);
Executou('L',2,tf, &i, &tle, &tee);
EntrouNaFila('L',2,tf, &i);
SaiuDaFila('E',3,tf, &i, &tle, &tee);
Executou('E',3,tf, &i, &tle, &tee);
EntrouNaFila('E',3,tf, &i);
SaiuDaFila('E',1,tf, &i, &tle, &tee);
Executou('E',1,tf, &i, &tle, &tee);
SaiuDaFila('E',2,tf, &i, &tle, &tee);
EntrouNaFila('E',1,tf, &i);
Executou('E',2,tf, &i, &tle, &tee);
EntrouNaFila('E',2,tf, &i);
SaiuDaFila('E',0,tf, &i, &tle, &tee);
Executou('E',0,tf, &i, &tle, &tee);
EntrouNaFila('E',0,tf, &i);
SaiuDaFila('L',1,tf, &i, &tle, &tee);
Executou('L',1,tf, &i, &tle, &tee);
EntrouNaFila('L',1,tf, &i);
SaiuDaFila('L',3,tf, &i, &tle, &tee);
SaiuDaFila('L',0,tf, &i, &tle, &tee);
Executou('L',0,tf, &i, &tle, &tee);
EntrouNaFila('L',0,tf, &i);
SaiuDaFila('L',2,tf, &i, &tle, &tee);
Executou('L',2,tf, &i, &tle, &tee);
EntrouNaFila('L',2,tf, &i);
Executou('L',3,tf, &i, &tle, &tee);
EntrouNaFila('L',3,tf, &i);
SaiuDaFila('E',3,tf, &i, &tle, &tee);
Executou('E',3,tf, &i, &tle, &tee);
SaiuDaFila('E',1,tf, &i, &tle, &tee);
Executou('E',1,tf, &i, &tle, &tee);
EntrouNaFila('E',1,tf, &i);
SaiuDaFila('E',2,tf, &i, &tle, &tee);
Executou('E',2,tf, &i, &tle, &tee);
EntrouNaFila('E',2,tf, &i);
SaiuDaFila('E',0,tf, &i, &tle, &tee);
Executou('E',0,tf, &i, &tle, &tee);
EntrouNaFila('E',0,tf, &i);
SaiuDaFila('L',1,tf, &i, &tle, &tee);
Executou('L',1,tf, &i, &tle, &tee);
EntrouNaFila('L',1,tf, &i);
SaiuDaFila('L',0,tf, &i, &tle, &tee);
Executou('L',0,tf, &i, &tle, &tee);
EntrouNaFila('L',0,tf, &i);
SaiuDaFila('L',2,tf, &i, &tle, &tee);
SaiuDaFila('L',3,tf, &i, &tle, &tee);
Executou('L',3,tf, &i, &tle, &tee);
EntrouNaFila('L',3,tf, &i);
EntrouNaFila('E',3,tf, &i);
Executou('L',2,tf, &i, &tle, &tee);
EntrouNaFila('L',2,tf, &i);
SaiuDaFila('E',1,tf, &i, &tle, &tee);
Executou('E',1,tf, &i, &tle, &tee);
EntrouNaFila('E',1,tf, &i);
SaiuDaFila('E',2,tf, &i, &tle, &tee);
Executou('E',2,tf, &i, &tle, &tee);
EntrouNaFila('E',2,tf, &i);
SaiuDaFila('E',0,tf, &i, &tle, &tee);
Executou('E',0,tf, &i, &tle, &tee);
EntrouNaFila('E',0,tf, &i);
SaiuDaFila('L',1,tf, &i, &tle, &tee);
Executou('L',1,tf, &i, &tle, &tee);
EntrouNaFila('L',1,tf, &i);
SaiuDaFila('L',0,tf, &i, &tle, &tee);
Executou('L',0,tf, &i, &tle, &tee);
EntrouNaFila('L',0,tf, &i);
SaiuDaFila('L',3,tf, &i, &tle, &tee);
Executou('L',3,tf, &i, &tle, &tee);
SaiuDaFila('E',3,tf, &i, &tle, &tee);
Executou('E',3,tf, &i, &tle, &tee);
EntrouNaFila('E',3,tf, &i);
SaiuDaFila('L',2,tf, &i, &tle, &tee);
Executou('L',2,tf, &i, &tle, &tee);
EntrouNaFila('L',2,tf, &i);
EntrouNaFila('L',3,tf, &i);
SaiuDaFila('E',1,tf, &i, &tle, &tee);
Executou('E',1,tf, &i, &tle, &tee);
EntrouNaFila('E',1,tf, &i);
SaiuDaFila('E',2,tf, &i, &tle, &tee);
Executou('E',2,tf, &i, &tle, &tee);
EntrouNaFila('E',2,tf, &i);
SaiuDaFila('E',0,tf, &i, &tle, &tee);
Executou('E',0,tf, &i, &tle, &tee);
EntrouNaFila('E',0,tf, &i);
SaiuDaFila('L',1,tf, &i, &tle, &tee);
Executou('L',1,tf, &i, &tle, &tee);
EntrouNaFila('L',1,tf, &i);
SaiuDaFila('L',0,tf, &i, &tle, &tee);
Executou('L',0,tf, &i, &tle, &tee);
EntrouNaFila('L',0,tf, &i);
SaiuDaFila('E',3,tf, &i, &tle, &tee);
Executou('E',3,tf, &i, &tle, &tee);
EntrouNaFila('E',3,tf, &i);
SaiuDaFila('L',2,tf, &i, &tle, &tee);
Executou('L',2,tf, &i, &tle, &tee);
EntrouNaFila('L',2,tf, &i);
SaiuDaFila('L',3,tf, &i, &tle, &tee);
Executou('L',3,tf, &i, &tle, &tee);
EntrouNaFila('L',3,tf, &i);
SaiuDaFila('E',1,tf, &i, &tle, &tee);
Executou('E',1,tf, &i, &tle, &tee);
EntrouNaFila('E',1,tf, &i);
SaiuDaFila('E',2,tf, &i, &tle, &tee);
Executou('E',2,tf, &i, &tle, &tee);
EntrouNaFila('E',2,tf, &i);
SaiuDaFila('E',0,tf, &i, &tle, &tee);
Executou('E',0,tf, &i, &tle, &tee);
EntrouNaFila('E',0,tf, &i);
SaiuDaFila('L',1,tf, &i, &tle, &tee);
SaiuDaFila('L',0,tf, &i, &tle, &tee);
Executou('L',0,tf, &i, &tle, &tee);
EntrouNaFila('L',0,tf, &i);
Executou('L',1,tf, &i, &tle, &tee);
EntrouNaFila('L',1,tf, &i);
SaiuDaFila('E',3,tf, &i, &tle, &tee);
Executou('E',3,tf, &i, &tle, &tee);
EntrouNaFila('E',3,tf, &i);
SaiuDaFila('L',2,tf, &i, &tle, &tee);
Executou('L',2,tf, &i, &tle, &tee);
EntrouNaFila('L',2,tf, &i);
SaiuDaFila('L',3,tf, &i, &tle, &tee);
Executou('L',3,tf, &i, &tle, &tee);
EntrouNaFila('L',3,tf, &i);
SaiuDaFila('E',1,tf, &i, &tle, &tee);
Executou('E',1,tf, &i, &tle, &tee);
EntrouNaFila('E',1,tf, &i);
SaiuDaFila('E',2,tf, &i, &tle, &tee);
Executou('E',2,tf, &i, &tle, &tee);
EntrouNaFila('E',2,tf, &i);
SaiuDaFila('E',0,tf, &i, &tle, &tee);
Executou('E',0,tf, &i, &tle, &tee);
EntrouNaFila('E',0,tf, &i);
SaiuDaFila('L',0,tf, &i, &tle, &tee);
Executou('L',0,tf, &i, &tle, &tee);
EntrouNaFila('L',0,tf, &i);
SaiuDaFila('L',1,tf, &i, &tle, &tee);
Executou('L',1,tf, &i, &tle, &tee);
EntrouNaFila('L',1,tf, &i);
SaiuDaFila('E',3,tf, &i, &tle, &tee);
Executou('E',3,tf, &i, &tle, &tee);
EntrouNaFila('E',3,tf, &i);
SaiuDaFila('L',2,tf, &i, &tle, &tee);
Executou('L',2,tf, &i, &tle, &tee);
EntrouNaFila('L',2,tf, &i);
SaiuDaFila('L',3,tf, &i, &tle, &tee);
Executou('L',3,tf, &i, &tle, &tee);
SaiuDaFila('E',1,tf, &i, &tle, &tee);
Executou('E',1,tf, &i, &tle, &tee);
EntrouNaFila('E',1,tf, &i);
SaiuDaFila('E',2,tf, &i, &tle, &tee);
EntrouNaFila('L',3,tf, &i);
Executou('E',2,tf, &i, &tle, &tee);
EntrouNaFila('E',2,tf, &i);
SaiuDaFila('E',0,tf, &i, &tle, &tee);
Executou('E',0,tf, &i, &tle, &tee);
EntrouNaFila('E',0,tf, &i);
SaiuDaFila('L',0,tf, &i, &tle, &tee);
Executou('L',0,tf, &i, &tle, &tee);
EntrouNaFila('L',0,tf, &i);
SaiuDaFila('L',1,tf, &i, &tle, &tee);
Executou('L',1,tf, &i, &tle, &tee);
EntrouNaFila('L',1,tf, &i);
SaiuDaFila('E',3,tf, &i, &tle, &tee);
Executou('E',3,tf, &i, &tle, &tee);
EntrouNaFila('E',3,tf, &i);
SaiuDaFila('L',2,tf, &i, &tle, &tee);
Executou('L',2,tf, &i, &tle, &tee);
EntrouNaFila('L',2,tf, &i);
SaiuDaFila('E',1,tf, &i, &tle, &tee);
Executou('E',1,tf, &i, &tle, &tee);
EntrouNaFila('E',1,tf, &i);
SaiuDaFila('L',3,tf, &i, &tle, &tee);
Executou('L',3,tf, &i, &tle, &tee);
EntrouNaFila('L',3,tf, &i);
SaiuDaFila('E',2,tf, &i, &tle, &tee);
Executou('E',2,tf, &i, &tle, &tee);
EntrouNaFila('E',2,tf, &i);
SaiuDaFila('E',0,tf, &i, &tle, &tee);
Executou('E',0,tf, &i, &tle, &tee);
EntrouNaFila('E',0,tf, &i);
SaiuDaFila('L',0,tf, &i, &tle, &tee);
Executou('L',0,tf, &i, &tle, &tee);
SaiuDaFila('L',1,tf, &i, &tle, &tee);
Executou('L',1,tf, &i, &tle, &tee);
EntrouNaFila('L',1,tf, &i);
SaiuDaFila('E',3,tf, &i, &tle, &tee);
Executou('E',3,tf, &i, &tle, &tee);
EntrouNaFila('E',3,tf, &i);
EntrouNaFila('L',0,tf, &i);
SaiuDaFila('L',2,tf, &i, &tle, &tee);
Executou('L',2,tf, &i, &tle, &tee);
EntrouNaFila('L',2,tf, &i);
SaiuDaFila('E',1,tf, &i, &tle, &tee);
Executou('E',1,tf, &i, &tle, &tee);
EntrouNaFila('E',1,tf, &i);
SaiuDaFila('L',3,tf, &i, &tle, &tee);
Executou('L',3,tf, &i, &tle, &tee);
EntrouNaFila('L',3,tf, &i);
SaiuDaFila('E',2,tf, &i, &tle, &tee);
Executou('E',2,tf, &i, &tle, &tee);
SaiuDaFila('E',0,tf, &i, &tle, &tee);
Executou('E',0,tf, &i, &tle, &tee);
EntrouNaFila('E',0,tf, &i);
EntrouNaFila('E',2,tf, &i);
SaiuDaFila('L',1,tf, &i, &tle, &tee);
Executou('L',1,tf, &i, &tle, &tee);
EntrouNaFila('L',1,tf, &i);
SaiuDaFila('E',3,tf, &i, &tle, &tee);
Executou('E',3,tf, &i, &tle, &tee);
SaiuDaFila('L',0,tf, &i, &tle, &tee);
Executou('L',0,tf, &i, &tle, &tee);
EntrouNaFila('L',0,tf, &i);
EntrouNaFila('E',3,tf, &i);
SaiuDaFila('L',2,tf, &i, &tle, &tee);
Executou('L',2,tf, &i, &tle, &tee);
EntrouNaFila('L',2,tf, &i);
SaiuDaFila('E',1,tf, &i, &tle, &tee);
Executou('E',1,tf, &i, &tle, &tee);
EntrouNaFila('E',1,tf, &i);
SaiuDaFila('L',3,tf, &i, &tle, &tee);
Executou('L',3,tf, &i, &tle, &tee);
EntrouNaFila('L',3,tf, &i);
SaiuDaFila('E',0,tf, &i, &tle, &tee);
Executou('E',0,tf, &i, &tle, &tee);
SaiuDaFila('E',2,tf, &i, &tle, &tee);
Executou('E',2,tf, &i, &tle, &tee);
SaiuDaFila('L',1,tf, &i, &tle, &tee);
SaiuDaFila('L',0,tf, &i, &tle, &tee);
Executou('L',0,tf, &i, &tle, &tee);
EntrouNaFila('L',0,tf, &i);
EntrouNaFila('E',0,tf, &i);
Executou('L',1,tf, &i, &tle, &tee);
SaiuDaFila('E',3,tf, &i, &tle, &tee);
EntrouNaFila('E',2,tf, &i);
Executou('E',3,tf, &i, &tle, &tee);
SaiuDaFila('L',2,tf, &i, &tle, &tee);
Executou('L',2,tf, &i, &tle, &tee);
EntrouNaFila('L',2,tf, &i);
EntrouNaFila('E',3,tf, &i);
EntrouNaFila('L',1,tf, &i);
SaiuDaFila('E',1,tf, &i, &tle, &tee);
Executou('E',1,tf, &i, &tle, &tee);
EntrouNaFila('E',1,tf, &i);
SaiuDaFila('L',3,tf, &i, &tle, &tee);
Executou('L',3,tf, &i, &tle, &tee);
EntrouNaFila('L',3,tf, &i);
SaiuDaFila('L',0,tf, &i, &tle, &tee);
Executou('L',0,tf, &i, &tle, &tee);
EntrouNaFila('L',0,tf, &i);
SaiuDaFila('E',0,tf, &i, &tle, &tee);
Executou('E',0,tf, &i, &tle, &tee);
EntrouNaFila('E',0,tf, &i);
SaiuDaFila('E',2,tf, &i, &tle, &tee);
Executou('E',2,tf, &i, &tle, &tee);
EntrouNaFila('E',2,tf, &i);
SaiuDaFila('L',2,tf, &i, &tle, &tee);
Executou('L',2,tf, &i, &tle, &tee);
SaiuDaFila('E',3,tf, &i, &tle, &tee);
Executou('E',3,tf, &i, &tle, &tee);
EntrouNaFila('E',3,tf, &i);
SaiuDaFila('L',1,tf, &i, &tle, &tee);
Executou('L',1,tf, &i, &tle, &tee);
SaiuDaFila('E',1,tf, &i, &tle, &tee);
Executou('E',1,tf, &i, &tle, &tee);
EntrouNaFila('E',1,tf, &i);
SaiuDaFila('L',3,tf, &i, &tle, &tee);
Executou('L',3,tf, &i, &tle, &tee);
EntrouNaFila('L',3,tf, &i);
EntrouNaFila('L',2,tf, &i);
EntrouNaFila('L',1,tf, &i);
SaiuDaFila('L',0,tf, &i, &tle, &tee);
Executou('L',0,tf, &i, &tle, &tee);
EntrouNaFila('L',0,tf, &i);
SaiuDaFila('E',0,tf, &i, &tle, &tee);
Executou('E',0,tf, &i, &tle, &tee);
EntrouNaFila('E',0,tf, &i);
SaiuDaFila('E',2,tf, &i, &tle, &tee);
Executou('E',2,tf, &i, &tle, &tee);
EntrouNaFila('E',2,tf, &i);
SaiuDaFila('E',3,tf, &i, &tle, &tee);
Executou('E',3,tf, &i, &tle, &tee);
SaiuDaFila('E',1,tf, &i, &tle, &tee);
Executou('E',1,tf, &i, &tle, &tee);
EntrouNaFila('E',1,tf, &i);
EntrouNaFila('E',3,tf, &i);
SaiuDaFila('L',3,tf, &i, &tle, &tee);
Executou('L',3,tf, &i, &tle, &tee);
EntrouNaFila('L',3,tf, &i);
SaiuDaFila('L',2,tf, &i, &tle, &tee);
Executou('L',2,tf, &i, &tle, &tee);
EntrouNaFila('L',2,tf, &i);
SaiuDaFila('L',1,tf, &i, &tle, &tee);
SaiuDaFila('L',0,tf, &i, &tle, &tee);
Executou('L',0,tf, &i, &tle, &tee);
EntrouNaFila('L',0,tf, &i);
Executou('L',1,tf, &i, &tle, &tee);
EntrouNaFila('L',1,tf, &i);
SaiuDaFila('E',0,tf, &i, &tle, &tee);
Executou('E',0,tf, &i, &tle, &tee);
EntrouNaFila('E',0,tf, &i);
SaiuDaFila('E',2,tf, &i, &tle, &tee);
Executou('E',2,tf, &i, &tle, &tee);
EntrouNaFila('E',2,tf, &i);
SaiuDaFila('E',1,tf, &i, &tle, &tee);
Executou('E',1,tf, &i, &tle, &tee);
EntrouNaFila('E',1,tf, &i);
SaiuDaFila('E',3,tf, &i, &tle, &tee);
Executou('E',3,tf, &i, &tle, &tee);
EntrouNaFila('E',3,tf, &i);
SaiuDaFila('L',3,tf, &i, &tle, &tee);
Executou('L',3,tf, &i, &tle, &tee);
EntrouNaFila('L',3,tf, &i);
SaiuDaFila('L',2,tf, &i, &tle, &tee);
SaiuDaFila('L',0,tf, &i, &tle, &tee);
Executou('L',0,tf, &i, &tle, &tee);
EntrouNaFila('L',0,tf, &i);
SaiuDaFila('L',1,tf, &i, &tle, &tee);
Executou('L',1,tf, &i, &tle, &tee);
EntrouNaFila('L',1,tf, &i);
Executou('L',2,tf, &i, &tle, &tee);
EntrouNaFila('L',2,tf, &i);
SaiuDaFila('E',0,tf, &i, &tle, &tee);
Executou('E',0,tf, &i, &tle, &tee);
EntrouNaFila('E',0,tf, &i);
SaiuDaFila('E',2,tf, &i, &tle, &tee);
Executou('E',2,tf, &i, &tle, &tee);
EntrouNaFila('E',2,tf, &i);
SaiuDaFila('E',1,tf, &i, &tle, &tee);
Executou('E',1,tf, &i, &tle, &tee);
SaiuDaFila('E',3,tf, &i, &tle, &tee);
Executou('E',3,tf, &i, &tle, &tee);
EntrouNaFila('E',3,tf, &i);
EntrouNaFila('E',1,tf, &i);
SaiuDaFila('L',3,tf, &i, &tle, &tee);
Executou('L',3,tf, &i, &tle, &tee);
EntrouNaFila('L',3,tf, &i);
SaiuDaFila('L',0,tf, &i, &tle, &tee);
Executou('L',0,tf, &i, &tle, &tee);
EntrouNaFila('L',0,tf, &i);
SaiuDaFila('L',1,tf, &i, &tle, &tee);
Executou('L',1,tf, &i, &tle, &tee);
EntrouNaFila('L',1,tf, &i);
SaiuDaFila('L',2,tf, &i, &tle, &tee);
Executou('L',2,tf, &i, &tle, &tee);
EntrouNaFila('L',2,tf, &i);
SaiuDaFila('E',0,tf, &i, &tle, &tee);
Executou('E',0,tf, &i, &tle, &tee);
SaiuDaFila('E',2,tf, &i, &tle, &tee);
Executou('E',2,tf, &i, &tle, &tee);
EntrouNaFila('E',2,tf, &i);
SaiuDaFila('E',3,tf, &i, &tle, &tee);
Executou('E',3,tf, &i, &tle, &tee);
SaiuDaFila('E',1,tf, &i, &tle, &tee);
Executou('E',1,tf, &i, &tle, &tee);
EntrouNaFila('E',1,tf, &i);
SaiuDaFila('L',3,tf, &i, &tle, &tee);
Executou('L',3,tf, &i, &tle, &tee);
EntrouNaFila('L',3,tf, &i);
SaiuDaFila('L',0,tf, &i, &tle, &tee);
Executou('L',0,tf, &i, &tle, &tee);
EntrouNaFila('L',0,tf, &i);
SaiuDaFila('L',1,tf, &i, &tle, &tee);
Executou('L',1,tf, &i, &tle, &tee);
EntrouNaFila('L',1,tf, &i);
SaiuDaFila('L',2,tf, &i, &tle, &tee);
Executou('L',2,tf, &i, &tle, &tee);
EntrouNaFila('L',2,tf, &i);
SaiuDaFila('E',2,tf, &i, &tle, &tee);
Executou('E',2,tf, &i, &tle, &tee);
EntrouNaFila('E',2,tf, &i);
EntrouNaFila('E',3,tf, &i);
SaiuDaFila('E',1,tf, &i, &tle, &tee);
Executou('E',1,tf, &i, &tle, &tee);
SaiuDaFila('L',3,tf, &i, &tle, &tee);
Executou('L',3,tf, &i, &tle, &tee);
EntrouNaFila('L',3,tf, &i);
EntrouNaFila('E',1,tf, &i);
SaiuDaFila('L',0,tf, &i, &tle, &tee);
Executou('L',0,tf, &i, &tle, &tee);
EntrouNaFila('L',0,tf, &i);
SaiuDaFila('L',1,tf, &i, &tle, &tee);
Executou('L',1,tf, &i, &tle, &tee);
EntrouNaFila('L',1,tf, &i);
SaiuDaFila('L',2,tf, &i, &tle, &tee);
Executou('L',2,tf, &i, &tle, &tee);
EntrouNaFila('L',2,tf, &i);
SaiuDaFila('E',2,tf, &i, &tle, &tee);
Executou('E',2,tf, &i, &tle, &tee);
EntrouNaFila('E',2,tf, &i);
SaiuDaFila('E',3,tf, &i, &tle, &tee);
Executou('E',3,tf, &i, &tle, &tee);
EntrouNaFila('E',3,tf, &i);
SaiuDaFila('L',3,tf, &i, &tle, &tee);
Executou('L',3,tf, &i, &tle, &tee);
EntrouNaFila('L',3,tf, &i);
SaiuDaFila('E',1,tf, &i, &tle, &tee);
Executou('E',1,tf, &i, &tle, &tee);
SaiuDaFila('L',0,tf, &i, &tle, &tee);
Executou('L',0,tf, &i, &tle, &tee);
SaiuDaFila('L',1,tf, &i, &tle, &tee);
Executou('L',1,tf, &i, &tle, &tee);
EntrouNaFila('L',1,tf, &i);
SaiuDaFila('L',2,tf, &i, &tle, &tee);
Executou('L',2,tf, &i, &tle, &tee);
EntrouNaFila('L',2,tf, &i);
SaiuDaFila('E',2,tf, &i, &tle, &tee);
Executou('E',2,tf, &i, &tle, &tee);
SaiuDaFila('E',3,tf, &i, &tle, &tee);
Executou('E',3,tf, &i, &tle, &tee);
EntrouNaFila('E',3,tf, &i);
EntrouNaFila('E',2,tf, &i);
SaiuDaFila('L',3,tf, &i, &tle, &tee);
Executou('L',3,tf, &i, &tle, &tee);
EntrouNaFila('L',3,tf, &i);
SaiuDaFila('L',1,tf, &i, &tle, &tee);
Executou('L',1,tf, &i, &tle, &tee);
SaiuDaFila('L',2,tf, &i, &tle, &tee);
Executou('L',2,tf, &i, &tle, &tee);
SaiuDaFila('E',3,tf, &i, &tle, &tee);
Executou('E',3,tf, &i, &tle, &tee);
EntrouNaFila('L',2,tf, &i);
SaiuDaFila('E',2,tf, &i, &tle, &tee);
Executou('E',2,tf, &i, &tle, &tee);
SaiuDaFila('L',3,tf, &i, &tle, &tee);
Executou('L',3,tf, &i, &tle, &tee);
SaiuDaFila('L',2,tf, &i, &tle, &tee);
Executou('L',2,tf, &i, &tle, &tee);
printf("Programa concorrente esta respeitando as condicoes do problema Leitor/Escritor e nao possui inanicao de threads!\n");}
